sudo: required
language: python
services:
  - docker
env:
  global:
    - CONCURRENCY=2
    - NOSE_FILTER="not windows"
    - INTEGRATIONS_DIR=$HOME/embedded
    - PIP_CACHE=$HOME/.cache/pip
    - SKIP_CLEANUP=true
    - VOLATILE_DIR=/tmp
    - DD_CASHER_DIR=/tmp/casher
    - AGENT_VERSION=2.1.6
    - CACHE_DIR=$HOME/.cache
    - CACHE_FILE_el6=$CACHE_DIR/el6.tar.gz
    - CACHE_FILE_el6_i386=$CACHE_DIR/el6_i386.tar.gz
    - CACHE_FILE_el7=$CACHE_DIR/el7.tar.gz
    - CACHE_FILE_precise=$CACHE_DIR/precise.tar.gz
    - CACHE_FILE_PACKAGES_LINUX=$CACHE_DIR/packages_linux.tar.gz
    - CACHE_FILE_PACKAGES_MAC=/tmp/sd-agent-latest.dmg
  matrix:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=core_integration
    - TRAVIS_FLAVOR=checks_mock
    - TRAVIS_FLAVOR=activemq
    - TRAVIS_FLAVOR=apache
    #- TRAVIS_FLAVOR=cassandra FLAVOR_VERSION=2.0.13
    #- TRAVIS_FLAVOR=cassandra FLAVOR_VERSION=2.1.3
    - TRAVIS_FLAVOR=couchdb
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=0.90.13
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.0.3
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.1.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.2.4
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.3.9
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.4.5
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.5.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.6.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.7.4
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=2.0.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=2.1.1
    #- TRAVIS_FLAVOR=etcd
    #- TRAVIS_FLAVOR=fluentd
    #- TRAVIS_FLAVOR=go_expvar
    # FIXME: cannot enable gearman on Travis right now
    # because it needs boost
    # - TRAVIS_FLAVOR=gearman
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.3.27
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.4.26
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.5.11
    #- TRAVIS_FLAVOR=kong FLAVOR_VERSION=0.8.1
    - TRAVIS_FLAVOR=lighttpd
    - TRAVIS_FLAVOR=memcache
    - TRAVIS_FLAVOR=mongo FLAVOR_VERSION=2.6.9
    - TRAVIS_FLAVOR=mongo FLAVOR_VERSION=3.0.1
    - TRAVIS_FLAVOR=mysql
    - TRAVIS_FLAVOR=network
    - TRAVIS_FLAVOR=nginx FLAVOR_VERSION=1.6.2
    - TRAVIS_FLAVOR=nginx FLAVOR_VERSION=1.7.11
    #- TRAVIS_FLAVOR=pgbouncer
    - TRAVIS_FLAVOR=phpfpm
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.0.19
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.1.15
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.2.10
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.3.6
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.4.1
    #- TRAVIS_FLAVOR=powerdns_recursor
    - TRAVIS_FLAVOR=rabbitmq
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.4.18
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.6.17
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.8.19
# Compilation takes too much time on Travis
#   - TRAVIS_FLAVOR=riak
    #- TRAVIS_FLAVOR=snmpd
    #- TRAVIS_FLAVOR=ssh
    - TRAVIS_FLAVOR=supervisord
    - TRAVIS_FLAVOR=sysstat
# FIXME: reenable, but right now cannot run on Travis because
# hugepages are enabled
#    - TRAVIS_FLAVOR=tokumx
    #- TRAVIS_FLAVOR=tomcat # JMX testing machine / need the other ones before
    - TRAVIS_FLAVOR=varnish FLAVOR_VERSION=3.0.7
    - TRAVIS_FLAVOR=varnish FLAVOR_VERSION=4.0.3
    - TRAVIS_FLAVOR=zookeeper FLAVOR_VERSION=3.4.7
    - TRAVIS_FLAVOR=zookeeper FLAVOR_VERSION=3.3.6

cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION.9
    - vendor/cache
    - $CACHE_DIR

before_install: echo "OVERRIDING TRAVIS STEPS"
install:  pip install softlayer-object-storage==0.5.4
before_script:
  - if [ "${TRAVIS_OS_NAME}" != "osx" ]; then sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static createrepo reprepro; fi
  - if [ "${TRAVIS_OS_NAME}" != "osx" ]; then echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register; fi
script: travis_retry ./.travis/build_installer.sh
after_failure:
  - echo "Logs from installation process come here / DEBUG LOGS"
  - cat /tmp/ci.log

jobs:
  include:
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
    - stage: build packages
      script: if [ "${TRAVIS_OS_NAME}" != "osx" ]; then travis_retry ./.travis/build_packages.sh; elif [ "${TRAVIS_OS_NAME}" == "osx" ]; then ./packaging/darwin/build_installer.sh; fi
      python: 2.7
    - os: osx
      language: generic
      python:
      env: TRAVIS_FLAVOR=default
    - stage: upload packages
      script: travis_retry ./.travis/upload_packages.sh
      python: 2.7
